### PR TITLE
Various performance improvements

### PR DESCRIPTION
**Pull request by V10lator**
No measurements at all, so take them with a grain of salt but cherry-pick what you think fits. :)

### CODE REVIEW

**Comment by jabelar** [comment]
Thanks, I appreciate the help.

A few comments and explanations related to some of the "clean up".

I see you like the "trinary" operator (?) for simple if return logic. I understand that it is compact and has some performance benefit, however the reason I use fully spaced out if-else bracketed code is because during debug I often like to put console statements (i.e. System.out.println()) which I'm sure you noticed. By having expanded bracket code blocks it is easier for me to quickly add debug statements. There is nothing strictly preventing that with trinary operator, but does start to affect readability. 

I'm not a big fan of using null as a valid/expected value. Maybe I'm old fashioned but to me a "null" is really a coding mistake (i.e. an uninitialized value). I realize that Minecraft is full of nullables though, and maybe passing null values is now in fashion, so I don't really mind it -- just not something I tend to do naturally. I do agree that checking for null instead of instanceof is probably higher performing though, so good idea.

The collision ray trace method is due to a feature I'm working on. I am working on a flashlight item, but then got the notices about issues so needed to address those (with your help thanks!). But just wanted to let you know that that isn't abandoned code..

Anyway, I will check out the pull request in more detail soon. I expect I will accept it as is.

**Comment by V10lator** [comment]
Originally I didn't want to reply to this but there's one thing to point out:

> I'm not a big fan of using null as a valid/expected value. Maybe I'm old fashioned but to me a "null" is really a coding mistake (i.e. an uninitialized value)

That's not true. While in Java your code won't compile if you try to use an unititalized variable in languages with direct memory access like C things will be worse: A unitialized variable points to random data in memory. In the best case the operating system will kill the program when it tries to access data it isn't allowed to while in the worst case you will read/write other variables of your app without noticing. Setting your variable to null on the other hand initializes it, so it no longer points to random memory but to a fake memory address which is there to be returned by functions and checked for afterwards. The == operand compares pointer adresses (which is why comparing strings with it has some caveats) so it's damn fast... ;)

**Comment by jabelar** [comment]
> Originally I didn't want to reply to this but there's one thing to point out:
> 
> > I'm not a big fan of using null as a valid/expected value. Maybe I'm old fashioned but to me a "null" is really a coding mistake (i.e. an uninitialized value)
> 
> That's not true. While in Java your code won't compile if you try to use an unititalized variable in languages with direct memory access like C things will be worse: A unitialized variable points to random data in memory. In the best case the operating system will kill the program when it tries to access data it isn't allowed to while in the worst case you will read/write other variables of your app without noticing. Setting your variable to null on the other hand initializes it, so it no longer points to random memory but to a fake memory address which is there to be returned by functions and checked for afterwards. The == operand compares pointer adresses (which is why comparing strings with it has some caveats) so it's damn fast... ;)

I'm not against setting it to null as an initialization to protect against weirder errors. I'm against using null as a valid state that has meaning for the program logic. It is okay if "null" means "uninitialized", but I don't like having code like "if x == null" throughout my code.

**Comment by jabelar** [comment]
Regarding big performance improvements, I'm wondering what the main type of lag people are experiencing is. I can think of the following:

1) Could be lighting updates on the client. The problem is that this can't really be avoided -- I'm placing and deleting blocks that change the lighting. I'm already only placing blocks when necessary so I don't think I'm really spamming it.

2) Could be server lag. I do have to loop through all the entities every tick, and worse I have to make a copy of all the collection of entities every tick to avoid concurrent modification errors. I'm wondering if keeping my own separate collection of entities (that is updated by entity join events and cleaned up occasionally for dead entities) would be better to avoid the copy. However, I'm nervous that I would get my collection out of sync. But may be worth a try.

3) The networking might be lagging. The block updates obviously need a packet. However, there should only be a packet when a new block is placed, so for example when an lighted entity is standing still it shouldn't spam and when it is moving you need to send the update. Network lag might cause some flicker or something but I can't quite see it creating overall actual FPS lag.

I'll profile more to figure out what is going on.

**Comment by jabelar** [comment]
Okay, some simple experiments are interesting.

Firstly, it seems that it is not the looping through the entities (1 above) because that happens every tick but the fps drops specifically when entity is emitting light.

Secondly, if light emitting entity stands still then there isn't an fps drop. So it is not anything about the block itself.

It does seem that fps drops when light emitting entity is moving. So I need to figure out if this is due to the block placement itself, or the lighting update associated with it, or something else.

**Comment by jabelar** [comment]
Okay, I narrowed it down. It is kinda interesting. Basically, I followed the code for the setBlockState() method and there wasn't a lot I could change that would speed things up while still retaining the functionality of actually changing the light. 

HOWEVER, when I was using the the F3 debug overlay and watching the FPS I saw that whenever I was moving and the FPS dropped that the number of chunk updates spikes. For some reason, placing my light blocks is causing a very large number of chunk updates. I'm going to post a question on the Modder Support forum to see if anyone knows why exactly that would happen. Otherwise I'll try to see if I can short-circuit that somehow. 

I don't think that placing a block should cause updates to like 50 chunks...although it seems that the vanilla code does indeed do that. There just isn't a lot of vanilla code that adds blocks every tick, so guess they might not have optimized it.

**Pull request merged**
